packages:
  - "packages/*"
catalog:
  typescript: ~5.6.2
  vite: ^6.0.1
  "@babel/parser": ^7.26.3
  "@babel/traverse": ^7.26.4
  "@vitest/ui": ^2.1.8
  "monaco-editor": ^0.52.0
  vitest: ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1
  vue: ^3.5.13
  "vue-tsc": ^2.1.10
  "vite-plugin-monaco-editor": ^1.1.0


