packages:
  - packages/*
catalog:
  "@babel/parser": ^7.26.3
  "@babel/traverse": ^7.26.4
  "@babel/types": ^7.26.3
  "@types/babel__traverse": ^7.20.6
  "@types/lodash": ^4.17.13
  "@vitejs/plugin-vue": ^5.2.1
  "@vitest/ui": ^2.1.8
  dayjs: ^1.11.13
  lodash: ^4.17.21
  monaco-editor: ""
  sass: ^1.82.0
  typescript: ~5.6.2
  unocss: ^0.65.1
  vite: ^6.0.1
  vite-plugin-dts: ^4.3.0
  vite-plugin-monaco-editor: ^1.1.0
  vitest: ^2.1.8
  vue: ^3.5.13
  vue-tsc: ^2.1.10
